markdown: kramdown
author:   Frank Mattes (postfach@frankmattes.de)
title:    GitHub Pages of Frank M. Mattes
defaults:
  - 
    scope:
      path: ""  # Alle Dateien
      type: "pages"
    value:      
      layout: "default"
  - 
    scope:
      path: ""  # Alle Dateien
      type: "posts"
    value:      
      layout: "posteintrag"

